name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
                          
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        npm install
        npm run build
      env:
        FB_API_KEY: ${{ secrets.FB_API_KEY }}
        FB_AUTH_DOMAIN: ${{ secrets.FB_AUTH_DOMAIN }}
        FB_PROJECT_ID: ${{ secrets.FB_PRJECT_ID }}
        FB_STORAGE_BUCKET: ${{ secrets.FB_STORAGE_BUCKET }}
        FB_MESSAGING_SENDER_ID: ${{ secrets.FB_MESSAGING_SENDER_ID }}
        FB_APP_ID: ${{ secrets.FB_APP_ID }}
        FB_MEASUREMENT_ID: ${{ secrets.FB_MEASUREMENT_ID }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: /